/**
 * Created by Amg on 2016/11/1.
 */

export const REQUEST_APP_START = 'REQUEST_APP_START';

export const FAILED_LOGIN_WITH_GUEST = 'FAILED_LOGIN_WITH_GUEST';

export const SUCCESS_LOGIN_WITH_GUEST = 'SUCCESS_LOGIN_WITH_GUEST';

export const SUCCESS_GET_GUEST_CHATNAME = 'SUCCESS_GET_GUEST_CHATNAME';

export const SUCCESS_LOGIN_WITH_TOKEN = 'SUCCESS_LOGIN_WITH_TOKEN';

export const SUCCESS_GET_AUTHORITY = 'SUCCESS_GET_AUTHORITY';

export const SUCCESS_GET_MESSAGE_CONFIG_WITH_TOKEN = 'SUCCESS_GET_MESSAGE_CONFIG_WITH_TOKEN';

export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';

export const REQUEST_GET_ALL_ROOM = 'REQUEST_GET_ALL_ROOM';

export const SUCCESS_GET_ALL_ROOM = 'SUCCESS_GET_ALL_ROOM';

export const FAILED_GET_ALL_ROOM = 'FAILED_GET_ALL_ROOM';

export const REQUEST_GET_ALL_ROOM_STATUS = 'REQUEST_GET_ALL_ROOM_STATUS';

export const SUCCESS_GET_ALL_ROOM_STATUS = 'SUCCESS_GET_ALL_ROOM_STATUS';

export const FAILED_GET_ALL_ROOM_STATUS = 'FAILED_GET_ALL_ROOM_STATUS';

export const SUCCESS_GET_ROOMINFO = 'SUCCESS_GET_ROOMINFO';

export const FAILED_GET_ROOMINFO = 'FAILED_GET_ROOMINFO';

export const SUCCESS_REFRESH_TOKEN = 'SUCCESS_REFRESH_TOKEN';

export const EXIT_ROOM = 'EXIT_ROOM';
