/**
 * Created by Amg on 2016/11/1.
 */


export const START_SCROLL_RUN_TO = 'START_SCROLL_RUN_TO';

export const END_SCROLL_TO_BOTTOM = 'END_SCROLL_TO_BOTTOM';

export const SUCCESS_GET_CHAT_RECORD = 'SUCCESS_GET_CHAT_RECORD';

export const FAILED_GET_CHAT_RECORD = 'FAILED_GET_CHAT_RECORD';

export const SUCCESS_GET_NEW_CHAT_RECORD = 'SUCCESS_GET_NEW_CHAT_RECORD';

export const FAILED_GET_NEW_CHAT_RECORD = 'FAILED_GET_NEW_CHAT_RECORD';

export const SUCCESS_GET_AUDIT_CHAT_RECORD_ID = 'SUCCESS_GET_AUDIT_CHAT_RECORD_ID';

export const FAILED_GET_NEW_AUDIT_RECORD_ID = 'FAILED_GET_NEW_AUDIT_RECORD_ID';

export const SUCCESS_GET_MORE_CHAT_RECORD = 'SUCCESS_GET_MORE_CHAT_RECORD';

export const FAILED_GET_MORE_CHAT_RECORD = 'FAILED_GET_MORE_CHAT_RECORD';

export const SUCCESS_AUDIT_MSG = 'SUCCESS_AUDIT_MSG';

export const FAILED_AUDIT_MSG = 'FAILED_AUDIT_MSG';

export const SUCCESS_SEND_MSG = 'SUCCESS_SEND_MSG';

export const FAILED_SEND_MSG = 'FAILED_SEND_MSG';

export const SUCCESS_KEEP_ONLINE = 'SUCCESS_KEEP_ONLINE';

